name: Secrets Demo

on:
  push:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Application
        env:
          MY_NAME: ${{ secrets.MY_NAME }}
        run: node app.js
